import { chromium, firefox, webkit } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';

const baseURL=process.env.MANUSCRIPT_URL||'http://127.0.0.1:4173/index.html';
const themes=['light','dark','oxford','typesetter','blueprint','ink'];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const check=(ok,msg)=>assert.ok(ok,msg);

async function visible(l){return (await l.count())>0&&await l.isVisible().catch(()=>false);}
async function closeModal(page){const x=page.locator('.modal-layer').first();if(await visible(x)){const c=x.locator('[data-action="modal-close"],.modal-close').first();if(await visible(c))await c.click({timeout:3000}).catch(()=>{});else await page.keyboard.press('Escape').catch(()=>{});await sleep(80);}}
async function closeCommand(page){const x=page.locator('.command-layer .command-palette').first();if(await visible(x)){await page.keyboard.press('Escape').catch(()=>{});await sleep(80);}}
async function clickVisible(page,sel){const ns=page.locator(sel);for(let i=0;i<await ns.count();i++){const n=ns.nth(i);await n.scrollIntoViewIfNeeded().catch(()=>{});if(await n.isVisible().catch(()=>false)){try{await n.click({timeout:3000});}catch{await n.evaluate(e=>e.click());}return n;}}throw new Error(`No visible element for ${sel}`);}
async function openEditor(page){await page.waitForFunction(()=>['landing','home','editor'].includes(document.documentElement.dataset.screen||''),null,{timeout:15000});let s=await page.locator('html').getAttribute('data-screen');if(s==='editor'){await page.waitForSelector('.cm-content',{timeout:15000});return;}if(s==='landing'){await closeModal(page);await clickVisible(page,'[data-action="home"]');await page.waitForFunction(()=>['home','editor'].includes(document.documentElement.dataset.screen||''),null,{timeout:15000});s=await page.locator('html').getAttribute('data-screen');if(s==='editor'){await page.waitForSelector('.cm-content',{timeout:15000});return;}}await closeModal(page);const b=page.locator('.modal-layer [data-action="onboarding-blank"]:visible').first();if(await b.count())await b.click({timeout:4000});else{await clickVisible(page,'[data-action="new"]');const post=page.locator('.modal-layer [data-action="onboarding-blank"]:visible').first();if(await post.count())await post.click({timeout:4000});}await page.waitForFunction(()=>document.documentElement.dataset.screen==='editor',null,{timeout:15000});await page.waitForSelector('.cm-content',{timeout:15000});}
async function setup(browserType,viewport,opts={}){const browser=await browserType.launch({headless:true});const context=await browser.newContext({viewport,isMobile:!!opts.isMobile,hasTouch:!!opts.hasTouch,deviceScaleFactor:opts.deviceScaleFactor||1,reducedMotion:opts.reducedMotion,forcedColors:opts.forcedColors});const page=await context.newPage();page.setDefaultTimeout(8000);const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(baseURL,{waitUntil:'load',timeout:45000});await openEditor(page);await closeModal(page);await closeCommand(page);await sleep(160);return{browser,context,page,errors};}
async function seriousAxe(page,label){await sleep(180);const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']).analyze();const serious=r.violations.filter(v=>['serious','critical'].includes(v.impact));check(serious.length===0,`${label}: serious Axe violations ${JSON.stringify(serious.map(v=>({id:v.id,impact:v.impact,targets:v.nodes.map(n=>n.target)})))}`);}
async function chooseTheme(page,theme){await closeModal(page);await page.setViewportSize({width:1440,height:900});await sleep(80);await clickVisible(page,'[data-action="theme"]:visible');const x=page.locator(`.theme-choice[data-theme-id="${theme}"]:visible`).first();await x.waitFor({state:'visible',timeout:4000});await x.click({timeout:4000});await page.waitForFunction(t=>document.documentElement.dataset.theme===t,theme,{timeout:5000});await closeModal(page);await sleep(220);}
async function layout(page){return page.evaluate(()=>{const vis=sel=>[...document.querySelectorAll(sel)].some(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;});const root=document.documentElement;return{w:root.clientWidth,h:root.clientHeight,sw:root.scrollWidth,mobileNav:vis('.mobile-bottom-nav'),mobileCommand:vis('.v430-mobile-command-trigger'),desktopCommand:vis('.v430-command-trigger'),editor:vis('.editor-pane'),preview:vis('.preview-pane'),screen:root.dataset.screen||'',theme:root.dataset.theme||''};});}
function assertLayout(g,label){check(g.sw<=g.w+2,`${label}: root horizontal overflow ${g.sw}/${g.w}`);const mobile=g.w<768;check(g.mobileNav===mobile,`${label}: mobile nav mismatch ${JSON.stringify(g)}`);check(g.mobileCommand===mobile,`${label}: mobile command mismatch ${JSON.stringify(g)}`);check(g.desktopCommand!==mobile,`${label}: desktop command mismatch ${JSON.stringify(g)}`);}
async function waitForResponsiveLayout(page,width,label,timeout=350){const started=Date.now();await page.waitForFunction(expected=>{const vis=sel=>[...document.querySelectorAll(sel)].some(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0;});const root=document.documentElement;if(root.clientWidth!==expected)return false;const mobile=root.clientWidth<768;return vis('.mobile-bottom-nav')===mobile&&vis('.v430-mobile-command-trigger')===mobile&&vis('.v430-command-trigger')!==mobile;},width,{timeout,polling:20});const g=await layout(page);assertLayout(g,label);return Date.now()-started;}
async function mobileSurfaceSemantics(page,originSel,rootSel,label){await page.setViewportSize({width:767,height:844});await sleep(180);const origin=page.locator(originSel).first();check(await visible(origin),`${label}: mobile origin missing`);await origin.click();const surface=page.locator(`${rootSel}:visible`).first();await surface.waitFor({state:'visible',timeout:4000});await sleep(150);check(await surface.getAttribute('role')==='dialog',`${label}: mobile role missing`);check(await surface.getAttribute('aria-modal')==='true',`${label}: mobile aria-modal missing`);check(await surface.getAttribute('data-v430-p6-mobile-dialog')==='true',`${label}: P6 ownership marker missing`);await page.setViewportSize({width:768,height:900});await sleep(180);check(await surface.getAttribute('data-v430-p6-mobile-dialog')===null,`${label}: P6 mobile marker leaked to desktop`);check(await surface.getAttribute('aria-modal')===null,`${label}: aria-modal leaked to desktop`);check(await surface.getAttribute('role')!=='dialog',`${label}: dialog role leaked to desktop`);}

async function contractAndDenseWidths(){const{browser,context,page,errors}=await setup(chromium,{width:1440,height:900});try{check(await page.locator('meta[name="manuscript-hardening-contract"]').count()===1,'P7 meta missing');check(await page.locator('meta[name="manuscript-hardening-contract"]').getAttribute('content')==='full-regression-responsive-v1','P7 meta value wrong');for(const marker of['#v430-p1-simplified-navigation','#v430-p2-compact-density','#v430-p3-focus-mode','#v430-p3-runtime','#v430-p4-command-palette','#v430-p4-runtime','#v430-p5-mobile-first','#v430-p5-runtime','#v430-p6-accessibility','#v430-p6-runtime','#v430-p7-responsive-hardening','#v430-p7-runtime'])check(await page.locator(marker).count()===1,`missing/duplicated ${marker}`);check(await page.evaluate(()=>window.__manuscriptV430P7?.version)==='full-regression-responsive-v1','P7 runtime missing');for(const width of[320,390,600,740,766,767,768,769,820,1024,1440,1920]){await page.setViewportSize({width,height:width<768?(width>=700?390:844):(width===768?1024:800)});await sleep(160);const g=await layout(page);assertLayout(g,`width ${width}`);if(width<768){const targets=await page.locator('.mobile-bottom-nav button:visible,.v430-mobile-command-trigger:visible').evaluateAll(ns=>ns.map(e=>{const r=e.getBoundingClientRect();return{w:r.width,h:r.height,text:(e.textContent||'').trim()};}));for(const t of targets)check(t.w>=44&&t.h>=44,`width ${width}: tap target below 44px ${JSON.stringify(t)}`);}}check(errors.length===0,`dense widths page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function semanticsAcrossBoundary(){const{browser,context,page,errors}=await setup(chromium,{width:767,height:844},{isMobile:true,hasTouch:true,deviceScaleFactor:2});try{await mobileSurfaceSemantics(page,'.mobile-bottom-nav [data-action="workflow-content"]:visible','.left-panel','Add 767->768');await page.setViewportSize({width:767,height:844});await sleep(180);await mobileSurfaceSemantics(page,'.mobile-bottom-nav [data-mobile="style"]:visible','.inspector','Style 767->768');check(errors.length===0,`semantic boundary page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function themeMatrix(){const{browser,context,page,errors}=await setup(chromium,{width:1440,height:900});try{for(const theme of themes){await chooseTheme(page,theme);check((await layout(page)).theme===theme,`theme ${theme}: state mismatch`);await seriousAxe(page,`theme ${theme} desktop`);if(theme==='typesetter'||theme==='blueprint'){await page.setViewportSize({width:390,height:844});await sleep(180);assertLayout(await layout(page),`theme ${theme} mobile`);await seriousAxe(page,`theme ${theme} mobile`);}}check(errors.length===0,`theme matrix page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function lowHeightCommands(){for(const viewport of[{width:768,height:420},{width:1024,height:420},{width:1024,height:500}]){const{browser,context,page,errors}=await setup(chromium,viewport);try{await page.locator('.cm-content').first().focus();await page.keyboard.press('Control+k');const p=page.locator('.command-palette:visible').first();await p.waitFor({state:'visible',timeout:4000});await sleep(150);const r=await p.evaluate(el=>{const x=el.getBoundingClientRect(),root=document.documentElement;return{top:x.top,bottom:x.bottom,left:x.left,right:x.right,w:x.width,h:x.height,vw:root.clientWidth,vh:root.clientHeight};});check(r.top>=-1&&r.left>=-1&&r.right<=r.vw+1&&r.bottom<=r.vh+1,`low-height ${viewport.width}x${viewport.height}: palette outside viewport ${JSON.stringify(r)}`);await seriousAxe(page,`low-height commands ${viewport.width}x${viewport.height}`);check(errors.length===0,`low-height ${viewport.width}: page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}}

async function controlledContent(){const{browser,context,page,errors}=await setup(chromium,{width:1024,height:768});try{const token='UNBROKEN_'+('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.repeat(18));const stress=`# P7-STRESS-SENTINEL\n\n${token}\n\nhttps://example.com/${'pathsegment/'.repeat(30)}\n\n\`\`\`text\n${'CODEWITHOUTBREAK'.repeat(35)}\n\`\`\`\n\nP7-STRESS-END`;const ed=page.locator('.cm-content').first();await ed.focus();await page.keyboard.press('Control+a');await page.keyboard.insertText(stress);await sleep(650);let inner=await ed.innerText();check(inner.includes('P7-STRESS-SENTINEL')&&inner.includes('P7-STRESS-END'),'stress content did not enter CodeMirror');let previewText=await page.locator('#preview-scroll').textContent();check(previewText?.includes('P7-STRESS-SENTINEL')&&previewText?.includes('P7-STRESS-END'),'stress content missing from preview');for(const viewport of[{width:1440,height:900},{width:768,height:1024},{width:767,height:844},{width:390,height:844},{width:320,height:568},{width:740,height:390}]){await page.setViewportSize(viewport);await sleep(220);const g=await layout(page);assertLayout(g,`stress ${viewport.width}x${viewport.height}`);inner=await ed.innerText();check(inner.includes('P7-STRESS-END'),`stress ${viewport.width}: document content lost`);check((await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)),`stress ${viewport.width}: root overflow`);}check(errors.length===0,`stress page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function textScaling(){for(const viewport of[{width:320,height:568},{width:390,height:844},{width:768,height:1024},{width:1024,height:768}]){const{browser,context,page,errors}=await setup(chromium,viewport,{isMobile:viewport.width<768,hasTouch:viewport.width<768});try{await page.addStyleTag({content:'html { font-size: 200% !important; }'});await sleep(300);const g=await layout(page);assertLayout(g,`200% ${viewport.width}`);const clipped=await page.evaluate(()=>[...document.querySelectorAll('button,a,[role="button"],[role="menuitem"]')].filter(el=>{const s=getComputedStyle(el),r=el.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0&&(el.scrollWidth>el.clientWidth+2||el.scrollHeight>el.clientHeight+2);}).map(el=>({cls:String(el.className||''),text:(el.textContent||'').replace(/\s+/g,' ').trim().slice(0,60)})).slice(0,10));check(clipped.length===0,`200% ${viewport.width}: clipped interactive labels ${JSON.stringify(clipped)}`);check(errors.length===0,`200% ${viewport.width}: page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}}

async function forcedColors(){const{browser,context,page,errors}=await setup(chromium,{width:390,height:844},{isMobile:true,hasTouch:true,reducedMotion:'reduce',forcedColors:'active'});try{assertLayout(await layout(page),'forced-colors mobile');await page.locator('.cm-content').first().focus();await page.keyboard.press('Control+k');await page.locator('.command-palette:visible').first().waitFor({state:'visible'});check(errors.length===0,`forced colors page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function webkitLiveBoundary(){const{browser,context,page,errors}=await setup(webkit,{width:768,height:844});try{let g=await layout(page);assertLayout(g,'webkit start768');await page.setViewportSize({width:767,height:844});const downMs=await waitForResponsiveLayout(page,767,'webkit resize767 settled',350);await page.setViewportSize({width:768,height:844});const upMs=await waitForResponsiveLayout(page,768,'webkit resize768 settled',350);console.log(`WebKit responsive settle: 768→767 ${downMs}ms, 767→768 ${upMs}ms`);check(errors.length===0,`webkit boundary page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}

async function repeatedCrossBrowser(){for(const[name,type]of[['firefox',firefox],['webkit',webkit]]){const{browser,context,page,errors}=await setup(type,{width:1024,height:800});try{for(const width of[769,768,767,390,320,767,768,769,1024,767,768]){await page.setViewportSize({width,height:width<768?844:800});await waitForResponsiveLayout(page,width,`${name} cycle ${width}`,name==='webkit'?350:250);}check(errors.length===0,`${name} cycle page errors ${errors.join(' | ')}`);}finally{await context.close();await browser.close();}}}

const tests=[['contract + dense widths',contractAndDenseWidths],['responsive semantic cleanup',semanticsAcrossBoundary],['theme contrast matrix',themeMatrix],['low-height commands',lowHeightCommands],['controlled long content',controlledContent],['200% text scaling',textScaling],['forced colors + reduced motion',forcedColors],['WebKit live 767/768 boundary',webkitLiveBoundary],['cross-browser repeated resize',repeatedCrossBrowser]];
let passed=0;for(const[name,fn]of tests){process.stdout.write(`Certifying P7 ${name}... `);try{await fn();passed++;console.log('PASS');}catch(e){console.log('FAIL');console.error(e?.stack||e);process.exitCode=1;break;}}
if(!process.exitCode)console.log(`V430-P7 full regression certification PASS — ${passed}/${tests.length} suites`);
